CREATE TABLE "organizations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(35) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "receive_endpoint" varchar(500) NOT NULL,
  "status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "certificates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" bigint NOT NULL,
  "public_key" text NOT NULL,
  "serial_number" varchar(255),
  "issued_at" timestamp,
  "expired_at" timestamp,
  "status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "sla_configurations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_priority" int NOT NULL,
  "max_receive_hours" int NOT NULL,
  "status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "documents" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_code" varchar(100) UNIQUE NOT NULL,
  "title" varchar(500),
  "summary" text,
  "extracted_metadata" jsonb,
  "sender_org_id" bigint NOT NULL,
  "document_type" varchar(50),
  "current_version" int DEFAULT 1,
  "status" varchar(30) DEFAULT 'ACTIVE',
  "version" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "document_versions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" bigint NOT NULL,
  "version_no" int NOT NULL,
  "storage_path" varchar(500) NOT NULL,
  "checksum" varchar(64) NOT NULL,
  "file_size" bigint,
  "update_reason" text,
  "created_by" varchar(100),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "document_receivers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" bigint NOT NULL,
  "receiver_org_id" bigint NOT NULL,
  "business_status_code" varchar(2) NOT NULL,
  "status_reason" text,
  "received_at" timestamp,
  "processed_at" timestamp,
  "version" int DEFAULT 0
);

CREATE TABLE "exchange_transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_code" varchar(50) UNIQUE NOT NULL,
  "document_id" bigint NOT NULL,
  "sender_org_id" bigint NOT NULL,
  "receiver_org_id" bigint NOT NULL,
  "priority" int NOT NULL,
  "current_status" varchar(30),
  "signature_status" varchar(30),
  "sla_deadline" timestamp,
  "version" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "status_histories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" bigint NOT NULL,
  "actor_org_id" bigint,
  "status_code" varchar(2) NOT NULL,
  "note" text,
  "changed_by" varchar(100),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "document_actions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" bigint NOT NULL,
  "transaction_id" bigint NOT NULL,
  "action_type" varchar(30),
  "action_status" varchar(30),
  "reason" text,
  "requested_by_org_id" bigint,
  "target_org_id" bigint,
  "created_at" timestamp DEFAULT (now()),
  "completed_at" timestamp
);

CREATE TABLE "document_action_receivers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action_id" bigint NOT NULL,
  "receiver_org_id" bigint NOT NULL,
  "response_status" varchar(30),
  "response_note" text,
  "responded_at" timestamp
);

CREATE TABLE "document_replacements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "replacement_document_id" bigint NOT NULL,
  "replaced_document_id" bigint NOT NULL,
  "reason" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "retry_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" bigint NOT NULL,
  "attempt_count" int DEFAULT 0,
  "next_retry_at" timestamp,
  "last_failure_reason" text,
  "status" varchar(30)
);

CREATE TABLE "notification_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(50),
  "target_admin" varchar(100),
  "payload" jsonb,
  "sent_at" timestamp,
  "status" varchar(30)
);

CREATE TABLE "audit_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" bigint,
  "document_id" bigint,
  "action" varchar(100) NOT NULL,
  "actor_type" varchar(30),
  "actor_id" varchar(100),
  "result" varchar(30),
  "detail" jsonb,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "organizations"."id" IS 'Khóa chính nội bộ';

COMMENT ON COLUMN "organizations"."code" IS 'Mã định danh QCVN 102 (VD: 000.00.00.H41)';

COMMENT ON COLUMN "organizations"."status" IS 'ACTIVE / SUSPENDED';

COMMENT ON COLUMN "certificates"."status" IS 'ACTIVE / EXPIRED / REVOKED';

COMMENT ON COLUMN "sla_configurations"."document_priority" IS '0: Thường, 1: Khẩn, 2: Thượng khẩn, 3: Hỏa tốc, 4: Hỏa tốc hẹn giờ';

COMMENT ON COLUMN "sla_configurations"."max_receive_hours" IS 'Thời gian tối đa phải tiếp nhận';

COMMENT ON COLUMN "documents"."extracted_metadata" IS 'Siêu dữ liệu linh hoạt & Kết quả OCR';

COMMENT ON COLUMN "documents"."status" IS 'ACTIVE / RECALLED / REPLACED / DELETED';

COMMENT ON COLUMN "documents"."version" IS 'Optimistic Locking';

COMMENT ON COLUMN "document_receivers"."business_status_code" IS 'Mã QCVN 102: 01 đến 06, 13, 15, 16';

COMMENT ON COLUMN "document_receivers"."status_reason" IS 'Lý do khi từ chối (02) hoặc từ chối lấy lại (16)';

COMMENT ON COLUMN "document_receivers"."version" IS 'Optimistic Locking';

COMMENT ON COLUMN "exchange_transactions"."priority" IS 'Dùng để phân luồng Queue';

COMMENT ON COLUMN "exchange_transactions"."current_status" IS 'RECEIVED, VALIDATED, ROUTED, DISPATCHED, DELIVERED, FAILED';

COMMENT ON COLUMN "exchange_transactions"."signature_status" IS 'VALID, INVALID, CERT_EXPIRED';

COMMENT ON COLUMN "exchange_transactions"."sla_deadline" IS 'Tính tự động từ bảng SLA';

COMMENT ON COLUMN "exchange_transactions"."version" IS 'Optimistic Locking';

COMMENT ON COLUMN "status_histories"."actor_org_id" IS 'Cơ quan đẩy trạng thái';

COMMENT ON COLUMN "document_actions"."action_type" IS 'RECALL, REPLACE';

COMMENT ON COLUMN "document_actions"."action_status" IS 'PENDING, APPROVED, REJECTED, COMPLETED';

COMMENT ON COLUMN "document_action_receivers"."response_status" IS 'PENDING, APPROVED, REJECTED';

COMMENT ON COLUMN "retry_jobs"."status" IS 'PENDING, RETRYING, EXHAUSTED, COMPLETED';

COMMENT ON COLUMN "notification_logs"."type" IS 'DLQ_ALERT, CERT_EXPIRY, SLA_BREACH, DAILY_REPORT';

COMMENT ON COLUMN "audit_logs"."transaction_id" IS 'Nullable cho event hệ thống';

COMMENT ON COLUMN "audit_logs"."document_id" IS 'Nullable';

COMMENT ON COLUMN "audit_logs"."actor_type" IS 'SYSTEM, ADMIN, ORGANIZATION';

COMMENT ON COLUMN "audit_logs"."result" IS 'SUCCESS, FAILURE';

ALTER TABLE "certificates" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("sender_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_versions" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_receivers" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_receivers" ADD FOREIGN KEY ("receiver_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exchange_transactions" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exchange_transactions" ADD FOREIGN KEY ("sender_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exchange_transactions" ADD FOREIGN KEY ("receiver_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "status_histories" ADD FOREIGN KEY ("transaction_id") REFERENCES "exchange_transactions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "status_histories" ADD FOREIGN KEY ("actor_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_actions" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_actions" ADD FOREIGN KEY ("transaction_id") REFERENCES "exchange_transactions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_actions" ADD FOREIGN KEY ("requested_by_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_actions" ADD FOREIGN KEY ("target_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_action_receivers" ADD FOREIGN KEY ("action_id") REFERENCES "document_actions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_action_receivers" ADD FOREIGN KEY ("receiver_org_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_replacements" ADD FOREIGN KEY ("replacement_document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_replacements" ADD FOREIGN KEY ("replaced_document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "retry_jobs" ADD FOREIGN KEY ("transaction_id") REFERENCES "exchange_transactions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("transaction_id") REFERENCES "exchange_transactions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
