CREATE TABLE "system_config" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "system_code" varchar(100) UNIQUE NOT NULL,
  "inbound_api_key" varchar(255) UNIQUE NOT NULL,
  "outbound_api_key" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);
