CREATE TABLE "outbox_event" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" uuid UNIQUE NOT NULL,
  "aggregate_type" varchar(100) NOT NULL,
  "aggregate_id" bigint NOT NULL,
  "event_type" varchar(100) NOT NULL,
  "payload" jsonb NOT NULL,
  "status" varchar(20) NOT NULL,
  "retry_count" int NOT NULL DEFAULT 0,
  "next_retry_at" timestamp,
  "created_at" timestamp NOT NULL,
  "processed_at" timestamp,
  "last_error" text
);
