CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "email" varchar(100) UNIQUE,
  "full_name" varchar(255),
  "phone_number" varchar(20),
  "status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "user_roles" (
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("user_id", "role_id"),
  CONSTRAINT "fk_user_roles_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT "fk_user_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(100) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "role_permissions" (
  "role_id" bigint NOT NULL,
  "permission_id" bigint NOT NULL,
  PRIMARY KEY ("role_id", "permission_id"),
  CONSTRAINT "fk_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT "fk_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

INSERT INTO "roles" ("code", "name", "description") VALUES
('ROLE_SUPER_ADMIN', 'System Administrator', 'Has full access to the system');

INSERT INTO "permissions" ("code", "name", "description") VALUES
('ORG_VIEW', 'Xem tổ chức', 'Xem danh sách và chi tiết tổ chức'),
('ORG_CREATE', 'Tạo tổ chức', 'Thêm mới tổ chức'),
('ORG_UPDATE', 'Sửa tổ chức', 'Cập nhật thông tin tổ chức'),
('ORG_DELETE', 'Xóa tổ chức', 'Xóa tổ chức khỏi hệ thống'),
('DOC_STATS', 'Thống kê văn bản', 'Thống kê văn bản đến và đi'),
('DOC_TRACKING', 'Theo dõi tracking', 'Theo dõi trạng thái luân chuyển văn bản');



