CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" text UNIQUE NOT NULL,
  "user_id" bigint NOT NULL,
  "expires_at" timestamp NOT NULL,
  "revoked" boolean DEFAULT FALSE NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  CONSTRAINT "fk_refresh_token_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);
